export enum ButterProtocol {
  UNI_V2 = 'V2',
  UNI_V3 = 'V3',
  QUICKSWAP = 'QUICKSWAP',
  SUSHISWAP = 'SUSHISWAP',
  PANCAKESWAP = 'PANCAKESWAP',
  CURVE = 'CURVE',
  REF = 'REF',
  HIVESWAP = 'HIVESWAP',
}
